{"name": "Ручка /api/v1/courier/login", "status": "passed", "description": "Логинимся с неправильным логином, ожидаем ошибку 404 и сообщение 'Учетная запись не найдена'", "steps": [{"name": "Запрос на авторизацию с неправильным логином", "status": "passed", "start": 1710620430306, "stop": 1710620430386}, {"name": "Проверки на статус и ответ", "status": "passed", "start": 1710620430386, "stop": 1710620430386}], "start": 1710620430306, "stop": 1710620430386, "uuid": "5186ba21-cdf5-4267-bc4e-a30d6a2db1b4", "historyId": "7674ec18c973a31a591397398ab64cf7", "testCaseId": "7674ec18c973a31a591397398ab64cf7", "fullName": "test_api.tests.test_login_courier.TestLoginCourier#test_login_courier_wrong_login", "labels": [{"name": "parentSuite", "value": "test_api.tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "LAPTOP-KS9V29SF"}, {"name": "thread", "value": "23412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api.tests.test_login_courier"}]}