{"name": "test_login_courier_wrong_login", "status": "passed", "description": "Создаём нового курьера, затем логинимся с неправильным логином, ожадаем ошибку 404 и сообщение 'Учетная запись не найдена'", "start": 1710079682749, "stop": 1710079682981, "uuid": "03397800-bff5-4bf0-bf2e-ed9aefa857ad", "historyId": "7674ec18c973a31a591397398ab64cf7", "testCaseId": "7674ec18c973a31a591397398ab64cf7", "fullName": "test_api.tests.test_login_courier.TestLoginCourier#test_login_courier_wrong_login", "labels": [{"name": "parentSuite", "value": "test_api.tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "LAPTOP-KS9V29SF"}, {"name": "thread", "value": "34208-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api.tests.test_login_courier"}]}