{"uuid": "acf86037-dd94-4587-92e3-a954752ed18d", "children": ["09fde5fb-24c2-4767-a6a3-164ae29b481d"], "befores": [{"name": "login_new_courier", "status": "broken", "statusDetails": {"message": "TypeError: unsupported callable\n", "trace": "  File \"C:\\Users\\79527\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\79527\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\79527\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\!Learning\\Yandex_auto\\qa_sprint_7\\conftest.py\", line 10, in login_new_courier\n    login_pass = Functions.register_new_courier_and_return_login_password()\n  File \"C:\\Users\\79527\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\allure_commons\\_allure.py\", line 189, in impl\n    params = func_parameters(func, *a, **kw)\n  File \"C:\\Users\\79527\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\allure_commons\\utils.py\", line 231, in func_parameters\n    arg_spec = inspect.getfullargspec(func)\n  File \"C:\\Users\\79527\\AppData\\Local\\Programs\\Python\\Python310\\lib\\inspect.py\", line 1295, in getfullargspec\n    raise TypeError('unsupported callable') from ex\n"}, "start": 1710612795939, "stop": 1710612795939}], "start": 1710612795939, "stop": 1710612796019}